# permissions for end users to view domains.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: domain-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8nnon
    app.kubernetes.io/part-of: k8nnon
    app.kubernetes.io/managed-by: kustomize
  name: domain-viewer-role
rules:
- apiGroups:
  - core.k8s.kannon.email
  resources:
  - domains
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.k8s.kannon.email
  resources:
  - domains/status
  verbs:
  - get
